// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Leave } from "./Leave";

export interface AvailableLeave { Leaves: Array<Leave>, }