// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { COADetailInsert } from "./COADetailInsert";

export interface COAInsert { coa_stype: string, coa_tdesc: string, coa_sreason: string, coa_semp: string, details: Array<COADetailInsert>, }