// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeaveDetail } from "./LeaveDetail";

export interface LeaveSummarywDetais { Lea_Sid: string, Lea_Ctr: bigint, Lea_Stype: string, Lev_Desc: string, Lea_Sfrm: string, Lea_Sto: string, Lea_Swithpay: number, Lea_Swithoutpay: number, Lea_Sreason: string, Lea_Semp: string, Lea_Sapplieddate: string, Lea_Sstatus: number, Lea_Sapprovedby: string | null, Lea_Sapprovedate: string | null, Lea_Logdate: string | null, Details: Array<LeaveDetail>, }