// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Access } from "./Access";
import type { Employee } from "./Employee";
import type { Schedule } from "./Schedule";

export interface EmployeeInfo { Employee: Employee, Access: Array<Access>, Schedules: Array<Schedule>, }