// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeaveSummarywDetais } from "./LeaveSummarywDetais";

export interface LeaveView { Leaves: Array<LeaveSummarywDetais>, }