// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface COADetail { coa_did: string, coa_dpk: string, coa_dctr: number, coa_dtype: string, coa_ddate: string, coa_dtime: string, }