// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { COADetail } from "./COADetail";

export interface COASummarywDetails { coa_sid: string, coa_stype: string, coa_sapplieddate: string, coa_tdesc: string, coa_stypedetail: string, coa_sreason: string, coa_semp: string, coa_sstatus: number, coa_sapprovedby: string | null, coa_sapprovedate: string | null, coa_logdate: string | null, details: Array<COADetail>, }