// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Employee { Emp_Id: string, Emp_Last: string, Emp_First: string, Emp_Mid: string | null, Emp_Dept: string, Emp_Loc: string, Emp_Pswd: string, }