// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LeaveDetail { Lea_Dpk: string, Lev_Dctr: bigint, Lea_Ddate: string, Lea_Dtype: string, Lea_Dampm: string | null, }