// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeaveDetailInsert } from "./LeaveDetailInsert";

export interface LeaveInsert { Emp_Id: string, Leave_Id: string, Date_From: string, Date_To: string, Reason: string, Details: Array<LeaveDetailInsert>, }