// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LeaveDetailInsert { Date: string, Date_Type: string, Am_Pm: string | null, }