// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeaveDetailInsert } from "./LeaveDetailInsert";

export interface LeaveUpdate { Lea_Sid: string, Emp_Id: string, Leave_Id: string, Lea_Swithpay: number, Lea_Swithoutpay: number, Date_From: string, Date_To: string, Reason: string, Details: Array<LeaveDetailInsert>, }